= TodoService - World's least awesome JSF Web View TODO

This will be a nice working TODO app by 2029..
For now it provides a trivial ToDo lister/editor for one person via HTML (JSF).

It is in the process of gaining a "signup" capability, but for now it will
be limited by use of a "signup PIN", intended for e.g., classroom use where
a batch of students need to sign up for developing apps that use the REST service.

TodoMore provides a REST interface, which will be awesome enough
that there will also be an Android Synch Service to go with it.

Uses ../TodoModel for its JPA Data; do mvn install in that project first.

You need to copy config-sample.properties to config.properties, and edit it.

Assuming you're using Wildfly 8 or 9 and PostGres 9,, just set up the datasource and do `mvn wildfly:deploy`


== Things do do.

Better UI!

Move away from container-managed security so it can more easily become multi-user.

== BUGS

The only reason this is split off from TodoService is that Java EE doesn't allow two
login-config elements, we need FORM for the JSF and BASIC for the REST. Sigh...
